version: '3.8'

services:
  db:
    image: postgres:16
    container_name: tourneytool-db
    restart: always
    environment:
      POSTGRES_USER: tourneyuser
      POSTGRES_PASSWORD: tourneysecret
      POSTGRES_DB: tourneydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: tourneytool-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://tourneyuser:tourneysecret@db:5432/tourneydb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: tourneytool-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
